### ISSUE TITLE
SwiftUI Button is overridden by SwiftUIX Button and keeps crashing? Xcode Beta issue

### ISSUE THREAD

**Issue by adamvnovak** [SwiftUIX/SwiftUIX#506] opened 2024-08-21 14:42 UTC
Just updated to the newest xcode beta 16.6 and start getting this issue
Haven't had any issues until now
I don't even have SwiftUIX imported in this file where the button exists

<img width="275" alt="Screenshot 2024-08-21 at 10 39 25 AM" src="https://github.com/user-attachments/assets/305fe4de-44dc-4f1b-a6a8-1f91461d6c19">
<img width="1248" alt="Screenshot 2024-08-21 at 10 39 27 AM" src="https://github.com/user-attachments/assets/49613262-3e68-480e-87fc-2b9482549230">
<img width="1246" alt="Screenshot 2024-08-21 at 10 39 31 AM" src="https://github.com/user-attachments/assets/648b0757-bd79-45c5-adc5-85aa71568937">
<img width="782" alt="Screenshot 2024-08-21 at 10 40 09 AM" src="https://github.com/user-attachments/assets/881ded54-e950-4d0f-ab27-48da8991663f">

**Comment by vmanot** [comment] 2024-08-22 19:14
@adamvnovak this is a dupe of #499 which was already fixed. Can you confirm if this is fixed for you on the tip of `master`?

**Comment by vmanot** [comment] 2024-08-30 08:46
Closing due to inactivity. This is fixed to the best of my knowledge.

**Closed by vmanot** 2024-08-30 08:46 UTC
