### ISSUE TITLE
.navigationSearchBar error - content displays above search

### ISSUE THREAD

**Issue by Michaelsafir** [SwiftUIX/SwiftUIX#201] opened 2021-02-06 21:24 UTC
```swift
        VStack{
            ScrollView{
                Text("Text")
                    .padding()
                Text("Text")
                    .padding()
                Text("Text")
                    .padding()
                Text("Text")
                    .padding()
                Text("Text")
                    .padding()
                Text("Text")
                    .padding()
                Text("Text")
                    .padding()
                Text("Text")
                    .padding()
                Text("Text")
                    .padding()
            }
            
            .navigationSearchBar { () -> SearchBar in
                SearchBar("Search", text: $search) { (edit) in
                    print(edit)
                } onCommit: {
                    print("commit")
                }
            }
        }
```

![Simulator Screen Shot - iPhone 12 - 2021-02-07 at 00 21 36](https://user-images.githubusercontent.com/33763394/107129982-88ab0280-68da-11eb-9403-6a1a9c54bd1f.png)

**Comment by vmanot** [comment] 2021-02-11 08:48
Unfortunately I have not found a fix to this bug yet - it seems to an Apple bug tied to the way `UINavigationController` interacts with child scroll views :/

**Comment by Michaelsafir** [comment] 2021-02-12 22:00
## This works fine

```swift
import Foundation
import SwiftUI
import UIKit

struct NavigationSearch<SearchResultsContent>: UIViewControllerRepresentable where SearchResultsContent : View {
    typealias UIViewControllerType = Wrapper
    
    @Binding var text: String
    
    private let onCancelButtonClicked: () -> Void
    private let onSearchButtonClicked: () -> Void
    
    private let searchResultsContent: () -> SearchResultsContent?

    init(text: Binding<String>, onCancelButtonClicked: @escaping () -> Void = {}, onSearchButtonClicked: @escaping () -> Void = {}, @ViewBuilder searchResultsContent: @escaping () -> SearchResultsContent? = { nil }) {
        self._text = text
        self.onCancelButtonClicked = onCancelButtonClicked
        self.onSearchButtonClicked = onSearchButtonClicked
        self.searchResultsContent = searchResultsContent
    }
    
    func makeCoordinator() -> Coordinator {
        Coordinator(representable: self)
    }

    func makeUIViewController(context: Context) -> Wrapper {
        Wrapper()
    }
    
    func updateUIViewController(_ wrapper: Wrapper, context: Context) {
        wrapper.searchController = context.coordinator.searchController
        wrapper.searchController?.searchBar.text = text
        
        if let searchResultsContent = self.searchResultsContent() {
            (wrapper.searchController?.searchResultsController as? UIHostingController<SearchResultsContent>)?.rootView = searchResultsContent
        }
    }
    
    class Coordinator: NSObject, UISearchResultsUpdating, UISearchBarDelegate {
        let representable: NavigationSearch
        
        let searchController: UISearchController
        
        init(representable: NavigationSearch) {
            self.representable = representable
            
            var searchResultsController: UIViewController? = nil

            if let searchResultsContent = representable.searchResultsContent() {
                searchResultsController = UIHostingController(rootView: searchResultsContent)
            }

            self.searchController = UISearchController(searchResultsController: searchResultsController)
            
            super.init()
            self.searchController.searchResultsUpdater = self
            self.searchController.searchBar.delegate = self
            self.searchController.searchBar.text = representable.text
        }
        
        // MARK: - UISearchResultsUpdating
        func updateSearchResults(for searchController: UISearchController) {
            guard let text = searchController.searchBar.text else { return }
            DispatchQueue.main.async { [weak self] in self?.representable.text = text }
        }
        
        // MARK: - UISearchBarDelegate
        func searchBarCancelButtonClicked(_ searchBar: UISearchBar) {
            DispatchQueue.main.async { self.representable.onCancelButtonClicked() }
        }

        func searchBarSearchButtonClicked(_ searchBar: UISearchBar) {
            DispatchQueue.main.async { self.representable.onSearchButtonClicked() }
        }
    }
    
    class Wrapper: UIViewController {
        var searchController: UISearchController? {
            get {
                self.parent?.navigationItem.searchController
            }
            set {
                self.parent?.navigationItem.searchController = newValue
            }
        }
    }
}
```

## How to apply:

```swift
NavigationView {
// some data view
}
.navigationBarTitle("Title", displayMode: .inline)
.overlay(NavigationSearch(text: $search, searchResultsContent: {
  VStack {
// content search
  }
}).frame(width: 0, height: 0))
```

**Comment by Michaelsafir** [comment] 2021-02-12 22:01
And also fact - your code works fine on IOS 14.1, but this strange behavior comes on upper versions on IOS. My code works fine on IOS 14.4) Maybe i helped somebody...

**Comment by vmanot** [comment] 2021-02-12 22:13
@Michaelsafir I'll take a look and maybe implement a runtime versioned fix, thanks! :)

**Comment by X901** [comment] 2021-04-01 09:23
This issue happened when you have NavigationView on Parent view
but you don't have NavigationView on Child view !

That mean it will work fine only if you have NavigationView on current view 

The issue is you cannot have NavigationView on both view Parent and also Child because you will get duplicate NavigationView

**Comment by vmanot** [comment] 2021-04-10 19:57
Closing this as this seems to be fixed now. Please reopen if it pops up again!

**Closed by vmanot** 2021-04-10 19:57 UTC
Labels: apple-bug
