### ISSUE TITLE
.windowOverlay cannot be closed

### ISSUE THREAD

**Issue by shiroI23** [SwiftUIX/SwiftUIX#500] opened 2024-07-30 06:19 UTC
Here is an example

```
struct ContentView: View {
    @State var isVisible = false
    var body: some View {
        ZStack{
            Text("Hello, World!")
                .onTapGesture {
                    isVisible.toggle()
                }
        }
        .windowOverlay(isVisible: $isVisible) {
            ZStack{
                Color.yellow
                    .onTapGesture {
                        isVisible = false
                        print("showView => \(isVisible)")
                    }
            }
        }
    }
}
```

**Comment by vmanot** [comment] 2024-08-19 09:26
Closing as a duplicate of #502, I'll fix this ASAP.

**Closed by vmanot** 2024-08-19 09:26 UTC
