### ISSUE TITLE
Xcode 12 fails to compile. Cannot find type 'ASAuthorization' in scope

### ISSUE THREAD

**Issue by prasannag** [SwiftUIX/SwiftUIX#127] opened 2020-08-29 02:23 UTC
In `AuthorizationAppleIDButton.swift`, compilation fails with 

> Cannot find type 'ASAuthorization' in scope

This used to compile up until beta 5.

**Comment by vmanot** [comment] 2020-08-29 12:49
@prasannag are you building from Xcode or from the command line? What target are you building for?

**Comment by Brett-Best** [comment] 2020-08-29 19:16
I was able to reproduce this by running:
`xcodebuild -scheme SwiftUIX build -configuration release -destination 'generic/platform=iOS Simulator’`

**Comment by prasannag** [comment] 2020-08-30 11:20
@vmanot @Brett-Best  I am seeing this problem when building in Xcode, you are not able to reproduce it with Xcode?

**Comment by vmanot** [comment] 2020-08-30 11:21
@prasannag I need the following information from you:
- Which Xcode version you're on.
- Which compile target you're building for.
- Whether you're building for **Debug** or **Release**.

**Comment by Brett-Best** [comment] 2020-08-30 11:21
@prasannag I could reproduce this compiling for the iOS Simulator using release configuration.

**Comment by prasannag** [comment] 2020-08-30 11:27
@vmanot 
- Xcode 12 Beta 6 (12A8189n)
- Building for iOS (iPhone only) 
- Debug build configuration

**Comment by vmanot** [comment] 2020-08-30 11:29
@prasannag I am not able to reproduce it. Are you on the latest `master`, or are you on `0.1`?

**Comment by prasannag** [comment] 2020-08-30 11:37
I can confirm that I am on latest master. Not sure how my configuration is different, will dig a bit more.

**Comment by vmanot** [comment] 2020-08-30 13:04
@prasannag we pushed some further updates to ease breakage on RELEASE builds for the simulator, but your case seems unique in that it's breaking on DEBUG as well. See if updating to master helps again.

**Comment by alexfringes** [comment] 2020-09-02 23:19
Seeing this also. Same setup as @prasannag mentioned above. However, I'm only running into it when building for SwiftUI Previews, not for the simulator (or onto device).

**Comment by vmanot** [comment] 2020-09-03 17:01
@alexfringes @prasannag @pteasima I've created a temporary branch [`xcode12b6-patch `](https://github.com/SwiftUIX/SwiftUIX/tree/asauthorization-xcode12b6-patch) removing it altogether. This is an Xcode bug, and there doesn't seem to be a way around it.

So while we wait for the next beta, feel free to hop on to this branch to get your archives/previews working.

**Comment by vmanot** [comment] 2020-09-15 20:57
Closing as Xcode 12GM seems to have fixed this.

**Comment by prasannag** [comment] 2020-09-16 13:19
Thanks @vmanot! Amazing work.

**Comment by vmanot** [comment] 2020-09-16 13:23
@prasannag spoke too soon, it's still present. 😅

**Closed** 2020-10-02 22:49 UTC
Labels: apple-bug, temporarily-patched, wontfix
