### ISSUE TITLE
Navigation problem 

### ISSUE THREAD

**Issue by tmp-dev99** [SwiftUIX/SwiftUIX#363] opened 2022-03-29 07:37 UTC
Hi!

Since SwiftUI X version 0.1.1, there are navigation problems, it can work on several screens but sometimes after several indentations it does not work anymore.
When the pop does not work.
I don't know if this has already been reported!

**Comment by vmanot** [comment] 2022-03-29 08:07
@tmp-dev99 please elaborate - what modifier/construct from SwiftUIX are you using, that you suspect may not be working as intended?

**Comment by tmp-dev99** [comment] 2022-03-29 08:52
I recover my navigator in the following way
`@Environment(\.navigator) private var navigator`
After i use it in the following way
`navigator?.push(OrderSuccess())` but it does not find the navigator and if I force unwrap it crashes

**Comment by iNathanZ** [comment] 2022-04-19 15:14
@vmanot 

Hello,
Same issue here, i had to use 0.1.0 but now that i upgraded my XCode to 13.3.1, i'm now synced to Master and i cannot navigator?.pop()
For the navigator?.push(), it works only for the first one.

Any idea of a workaround or a fix ?

**Comment by mistralaix** [comment] 2022-04-25 07:03
Hello, same problem here, any idea how to fix it?

**Comment by vmanot** [comment] 2022-04-25 11:17
@tmp-dev99 @iNathanZ @mistralaix I'm working on a fix, will release it today/tomorrow.

**Comment by vmanot** [comment] 2022-05-01 17:20
This is now fixed on the tip of `master`. Remember to add `_resolveAppKitOrUIKitViewControllerIfAvailable()` _outside_ of the view you are using `@Environment(\.navigator)` from (this is now also documented at the environment value declaration).

**Closed by vmanot** 2022-05-01 17:20 UTC
Labels: bug
