### ISSUE TITLE
SectionNavigator navigate destination closure called two times

### ISSUE THREAD

**Issue by mrsunx** [SwiftUIX/SwiftUIX#49] opened 2020-04-15 09:49 UTC
`
    var body: some View {
        Text("hello world")
            .onTapGesture {
                self.isActive = true
            }
            .navigate(isActive: $isActive, onDismiss: nil, to: {
                Text("hello")
            })
    }
`
Text("hello") closure called two times

**Comment by vmanot** [comment] 2020-04-15 13:32
@mrsunx thank you for pointing it out! I'm currently swamped with other work, will look into it whenever I can. It may also be a SwiftUI behavioral change/regression between minor iOS versions, please also specify which version of iOS/Xcode you are using to reproduce this bug :)

**Comment by mrsunx** [comment] 2020-04-16 01:17
Thank you for your reply.
Xcode version: 11.4
iOS 13.4, iPhone 8 Plus.

**Comment by vmanot** [comment] 2020-05-11 12:24
I've investigated this, and it seems to be a SwiftUI bug, unfortunately. Closing this issue as I cannot fix it, feel free to reopen if you find a workaround.

**Closed by vmanot** 2020-05-11 12:24 UTC
Labels: apple-bug, bug, wontfix
