### ISSUE TITLE
SDK is crashing on Xcode 16.0

### ISSUE THREAD

**Issue by Faizan-Seera** [SwiftUIX/SwiftUIX#515] opened 2024-09-19 12:23 UTC
I update to the Xcode to 16.0 and after that sdk start crashing.

<img width="1920" alt="Screenshot 2024-09-19 at 4 20 24 PM (2)" src="https://github.com/user-attachments/assets/333cdc0a-a35f-4b3c-8752-acda4c84189f">

<img width="1918" alt="Screenshot 2024-09-19 at 4 23 46 PM" src="https://github.com/user-attachments/assets/4dfb522b-35cc-44b9-bca7-b1bb22c422f1">

**Comment by muradtries** [comment] 2024-09-20 19:05
I'm also having this issue

**Comment by adammagana** [comment] 2024-09-23 16:53
I managed to temporarily work around this issue in my code by using the `Button(role:action:label:)` initializer instead. I simply passed  `nil` for the `role` parameter and the issue went away.

**Comment by vmanot** [comment] 2024-09-25 16:38
@Faizan-Seera @adammagana thanks for the patience everyone, I'll have a fix out for this by tomorrow.

**Comment by mercierj** [comment] 2024-10-01 12:06
Any news on this issue ? @vmanot  
Thanks for maintaining

**Comment by vmanot** [comment] 2024-10-01 12:18
@mercierj could you check `0.2.3` and see if the issue is fixed for you?

**Comment by adammagana** [comment] 2024-10-01 14:44
Thank you @vmanot 💗

**Comment by vmanot** [comment] 2024-10-05 07:29
@Faizan-Seera I'm closing this issue, feel free to reopen if it persists.

**Closed by vmanot** 2024-10-05 07:29 UTC

**Comment by Faizan-Seera** [comment] 2024-10-07 13:24
@vmanot yes issue is solved. Thanks buddy.
