### ISSUE TITLE
.OnCancel will dismiss view !

### ISSUE THREAD

**Issue by X901** [SwiftUIX/SwiftUIX#226] opened 2021-04-01 09:33 UTC
Hi, 
I notice when I tap on cancel button in searchbar it will close the whole view
this only happened with child view
I have **view1** (have searchbar on it) >> **view2** >> **view** 3 (I have searchbar on it)
when I tab cancel button in **veiw3** it will return to  **view1**

but with parent view(**view1**) it won't do anything so this issue happened only with child view

**Comment by vmanot** [comment] 2021-04-01 12:35
@X901 would it be possible for you to attach a sample repo? `searchBar.endEditing(true)` is the only other call I make in `SearchBar`'s cancel handler, it shouldn't be causing any views to dismiss.

**Comment by vmanot** [comment] 2021-04-10 19:57
Closing this for now as I am unable to reproduce it, please feel free to reopen with a sample repro :)

**Closed by vmanot** 2021-04-10 19:57 UTC
